"""empty message

Revision ID: 91712acc91f1
Revises: b065c1abfd94
Create Date: 2020-06-10 12:21:56.406099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91712acc91f1'
down_revision = 'b065c1abfd94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store', sa.Column('test', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
